# Generated by Django 4.0.2 on 2022-11-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sentance', models.TextField()),
                ('label', models.IntegerField(choices=[(1, 'True'), (0, 'False')])),
            ],
        ),
        migrations.CreateModel(
            name='NER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sentance', models.IntegerField()),
                ('word', models.TextField()),
                ('tag', models.TextField(choices=[('O', 'O'), ('Object', 'Object'), ('Attribute', 'Attribute'), ('Function', 'Function'), ('Operator', 'Operator'), ('Value', 'Value'), ('Unit', 'Unit')])),
            ],
        ),
        migrations.CreateModel(
            name='Sentance_for_classification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sentance', models.TextField()),
                ('classified_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sentance_for_tagging',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sentance', models.TextField()),
                ('tagged_by', models.TextField()),
            ],
        ),
    ]
