# Generated by Django 4.0.2 on 2022-11-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genestorage',
            name='refGene_AA',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='genestorage',
            name='refGene_splice',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
